### ISSUE TITLE
feature-createissue

### ISSUE THREAD

**Issue by albertanguyen** [albertanguyen/github-issuePage.github.io#8]
* Create a new issue via a modal for the repository, by clicking on a "new issue" button. Clicking on this button will pop open a modal that asks for the requisite fields.
* The user is able to write in markdown in the write field and preview it in html
* Create the issue (for example, not supplying all required parameters) if there is an error , there should be a nice error message to.

**Comment by huynhtehoa** [comment]
-phenomenally solved by Anh and Dai. both pulled out amazing works and rocked this project
- error message has minor issue (it only works for the first card)
